/* 自动生成:node scripts/gen-icon-package.mjs —— 勿手改 */
import '@fluentui/react-icons/headless/styles.css';
import { wrapIcon } from './wrap';
import { HomeRegular as HomeRegularBase, HomeFilled as HomeFilledBase } from '@fluentui/react-icons/headless/svg/home';
import { SettingsRegular as SettingsRegularBase, SettingsFilled as SettingsFilledBase } from '@fluentui/react-icons/headless/svg/settings';
import { NavigationRegular as NavigationRegularBase, NavigationFilled as NavigationFilledBase } from '@fluentui/react-icons/headless/svg/navigation';
import { PanelLeftRegular as PanelLeftRegularBase, PanelLeftFilled as PanelLeftFilledBase } from '@fluentui/react-icons/headless/svg/panel-left';
import { AppsRegular as AppsRegularBase, AppsFilled as AppsFilledBase } from '@fluentui/react-icons/headless/svg/apps';
import { WindowRegular as WindowRegularBase, WindowFilled as WindowFilledBase } from '@fluentui/react-icons/headless/svg/window';
import { FullScreenMaximizeRegular as FullScreenMaximizeRegularBase } from '@fluentui/react-icons/headless/svg/full-screen-maximize';
import { FullScreenMinimizeRegular as FullScreenMinimizeRegularBase } from '@fluentui/react-icons/headless/svg/full-screen-minimize';
import { AddRegular as AddRegularBase, AddFilled as AddFilledBase } from '@fluentui/react-icons/headless/svg/add';
import { SubtractRegular as SubtractRegularBase, SubtractFilled as SubtractFilledBase } from '@fluentui/react-icons/headless/svg/subtract';
import { DismissRegular as DismissRegularBase, DismissFilled as DismissFilledBase } from '@fluentui/react-icons/headless/svg/dismiss';
import { CheckmarkRegular as CheckmarkRegularBase, CheckmarkFilled as CheckmarkFilledBase } from '@fluentui/react-icons/headless/svg/checkmark';
import { SearchRegular as SearchRegularBase, SearchFilled as SearchFilledBase } from '@fluentui/react-icons/headless/svg/search';
import { EditRegular as EditRegularBase, EditFilled as EditFilledBase } from '@fluentui/react-icons/headless/svg/edit';
import { DeleteRegular as DeleteRegularBase, DeleteFilled as DeleteFilledBase } from '@fluentui/react-icons/headless/svg/delete';
import { SaveRegular as SaveRegularBase, SaveFilled as SaveFilledBase } from '@fluentui/react-icons/headless/svg/save';
import { CopyRegular as CopyRegularBase, CopyFilled as CopyFilledBase } from '@fluentui/react-icons/headless/svg/copy';
import { CutRegular as CutRegularBase, CutFilled as CutFilledBase } from '@fluentui/react-icons/headless/svg/cut';
import { ClipboardRegular as ClipboardRegularBase, ClipboardFilled as ClipboardFilledBase } from '@fluentui/react-icons/headless/svg/clipboard';
import { ShareRegular as ShareRegularBase, ShareFilled as ShareFilledBase } from '@fluentui/react-icons/headless/svg/share';
import { FilterRegular as FilterRegularBase, FilterFilled as FilterFilledBase } from '@fluentui/react-icons/headless/svg/filter';
import { PrintRegular as PrintRegularBase, PrintFilled as PrintFilledBase } from '@fluentui/react-icons/headless/svg/print';
import { PinRegular as PinRegularBase, PinFilled as PinFilledBase } from '@fluentui/react-icons/headless/svg/pin';
import { LinkRegular as LinkRegularBase, LinkFilled as LinkFilledBase } from '@fluentui/react-icons/headless/svg/link';
import { ChevronDownRegular as ChevronDownRegularBase, ChevronDownFilled as ChevronDownFilledBase } from '@fluentui/react-icons/headless/svg/chevron-down';
import { ChevronUpRegular as ChevronUpRegularBase, ChevronUpFilled as ChevronUpFilledBase } from '@fluentui/react-icons/headless/svg/chevron-up';
import { ChevronLeftRegular as ChevronLeftRegularBase, ChevronLeftFilled as ChevronLeftFilledBase } from '@fluentui/react-icons/headless/svg/chevron-left';
import { ChevronRightRegular as ChevronRightRegularBase, ChevronRightFilled as ChevronRightFilledBase } from '@fluentui/react-icons/headless/svg/chevron-right';
import { ArrowLeftRegular as ArrowLeftRegularBase, ArrowLeftFilled as ArrowLeftFilledBase } from '@fluentui/react-icons/headless/svg/arrow-left';
import { ArrowUpRegular as ArrowUpRegularBase, ArrowUpFilled as ArrowUpFilledBase } from '@fluentui/react-icons/headless/svg/arrow-up';
import { ArrowDownRegular as ArrowDownRegularBase, ArrowDownFilled as ArrowDownFilledBase } from '@fluentui/react-icons/headless/svg/arrow-down';
import { ArrowSortRegular as ArrowSortRegularBase, ArrowSortFilled as ArrowSortFilledBase } from '@fluentui/react-icons/headless/svg/arrow-sort';
import { ArrowUploadRegular as ArrowUploadRegularBase, ArrowUploadFilled as ArrowUploadFilledBase } from '@fluentui/react-icons/headless/svg/arrow-upload';
import { ArrowDownloadRegular as ArrowDownloadRegularBase, ArrowDownloadFilled as ArrowDownloadFilledBase } from '@fluentui/react-icons/headless/svg/arrow-download';
import { ArrowSyncRegular as ArrowSyncRegularBase, ArrowSyncFilled as ArrowSyncFilledBase } from '@fluentui/react-icons/headless/svg/arrow-sync';
import { ArrowClockwiseRegular as ArrowClockwiseRegularBase, ArrowClockwiseFilled as ArrowClockwiseFilledBase } from '@fluentui/react-icons/headless/svg/arrow-clockwise';
import { InfoRegular as InfoRegularBase, InfoFilled as InfoFilledBase } from '@fluentui/react-icons/headless/svg/info';
import { CheckmarkCircleRegular as CheckmarkCircleRegularBase, CheckmarkCircleFilled as CheckmarkCircleFilledBase } from '@fluentui/react-icons/headless/svg/checkmark-circle';
import { WarningRegular as WarningRegularBase, WarningFilled as WarningFilledBase } from '@fluentui/react-icons/headless/svg/warning';
import { ErrorCircleRegular as ErrorCircleRegularBase, ErrorCircleFilled as ErrorCircleFilledBase } from '@fluentui/react-icons/headless/svg/error-circle';
import { QuestionCircleRegular as QuestionCircleRegularBase, QuestionCircleFilled as QuestionCircleFilledBase } from '@fluentui/react-icons/headless/svg/question-circle';
import { AlertRegular as AlertRegularBase, AlertFilled as AlertFilledBase } from '@fluentui/react-icons/headless/svg/alert';
import { ImageRegular as ImageRegularBase, ImageFilled as ImageFilledBase } from '@fluentui/react-icons/headless/svg/image';
import { DocumentRegular as DocumentRegularBase, DocumentFilled as DocumentFilledBase } from '@fluentui/react-icons/headless/svg/document';
import { FolderRegular as FolderRegularBase, FolderFilled as FolderFilledBase } from '@fluentui/react-icons/headless/svg/folder';
import { FolderOpenRegular as FolderOpenRegularBase, FolderOpenFilled as FolderOpenFilledBase } from '@fluentui/react-icons/headless/svg/folder-open';
import { EyeRegular as EyeRegularBase, EyeFilled as EyeFilledBase } from '@fluentui/react-icons/headless/svg/eye';
import { EyeOffRegular as EyeOffRegularBase, EyeOffFilled as EyeOffFilledBase } from '@fluentui/react-icons/headless/svg/eye-off';
import { ZoomInRegular as ZoomInRegularBase, ZoomInFilled as ZoomInFilledBase } from '@fluentui/react-icons/headless/svg/zoom-in';
import { ZoomOutRegular as ZoomOutRegularBase, ZoomOutFilled as ZoomOutFilledBase } from '@fluentui/react-icons/headless/svg/zoom-out';
import { PlayRegular as PlayRegularBase, PlayFilled as PlayFilledBase } from '@fluentui/react-icons/headless/svg/play';
import { PauseRegular as PauseRegularBase, PauseFilled as PauseFilledBase } from '@fluentui/react-icons/headless/svg/pause';
import { MoreHorizontalRegular as MoreHorizontalRegularBase, MoreHorizontalFilled as MoreHorizontalFilledBase } from '@fluentui/react-icons/headless/svg/more-horizontal';
import { OptionsRegular as OptionsRegularBase, OptionsFilled as OptionsFilledBase } from '@fluentui/react-icons/headless/svg/options';
import { CalendarLtrRegular as CalendarLtrRegularBase, CalendarLtrFilled as CalendarLtrFilledBase } from '@fluentui/react-icons/headless/svg/calendar-ltr';
import { GridRegular as GridRegularBase, GridFilled as GridFilledBase } from '@fluentui/react-icons/headless/svg/grid';
import { ListRegular as ListRegularBase, ListFilled as ListFilledBase } from '@fluentui/react-icons/headless/svg/list';
import { TableRegular as TableRegularBase, TableFilled as TableFilledBase } from '@fluentui/react-icons/headless/svg/table';
import { ChatRegular as ChatRegularBase, ChatFilled as ChatFilledBase } from '@fluentui/react-icons/headless/svg/chat';
import { MailRegular as MailRegularBase, MailFilled as MailFilledBase } from '@fluentui/react-icons/headless/svg/mail';
import { PersonRegular as PersonRegularBase, PersonFilled as PersonFilledBase } from '@fluentui/react-icons/headless/svg/person';
import { TagRegular as TagRegularBase, TagFilled as TagFilledBase } from '@fluentui/react-icons/headless/svg/tag';
import { BookmarkRegular as BookmarkRegularBase, BookmarkFilled as BookmarkFilledBase } from '@fluentui/react-icons/headless/svg/bookmark';
import { FlagRegular as FlagRegularBase, FlagFilled as FlagFilledBase } from '@fluentui/react-icons/headless/svg/flag';
import { StarRegular as StarRegularBase, StarFilled as StarFilledBase } from '@fluentui/react-icons/headless/svg/star';
import { HeartRegular as HeartRegularBase, HeartFilled as HeartFilledBase } from '@fluentui/react-icons/headless/svg/heart';
import { LockClosedRegular as LockClosedRegularBase, LockClosedFilled as LockClosedFilledBase } from '@fluentui/react-icons/headless/svg/lock-closed';
import { ColorRegular as ColorRegularBase, ColorFilled as ColorFilledBase } from '@fluentui/react-icons/headless/svg/color';
import { PaintBrushRegular as PaintBrushRegularBase, PaintBrushFilled as PaintBrushFilledBase } from '@fluentui/react-icons/headless/svg/paint-brush';
import { TextFontRegular as TextFontRegularBase, TextFontFilled as TextFontFilledBase } from '@fluentui/react-icons/headless/svg/text-font';
import { KeyboardRegular as KeyboardRegularBase, KeyboardFilled as KeyboardFilledBase } from '@fluentui/react-icons/headless/svg/keyboard';
import { CodeRegular as CodeRegularBase, CodeFilled as CodeFilledBase } from '@fluentui/react-icons/headless/svg/code';
import { StackRegular as StackRegularBase, StackFilled as StackFilledBase } from '@fluentui/react-icons/headless/svg/stack';
import { CompassNorthwestRegular as CompassNorthwestRegularBase, CompassNorthwestFilled as CompassNorthwestFilledBase } from '@fluentui/react-icons/headless/svg/compass-northwest';
import { MaximizeRegular as MaximizeRegularBase, MaximizeFilled as MaximizeFilledBase } from '@fluentui/react-icons/headless/svg/maximize';
import { SquareMultipleRegular as SquareMultipleRegularBase, SquareMultipleFilled as SquareMultipleFilledBase } from '@fluentui/react-icons/headless/svg/square-multiple';
import { ClockRegular as ClockRegularBase, ClockFilled as ClockFilledBase } from '@fluentui/react-icons/headless/svg/clock';
import { HistoryRegular as HistoryRegularBase, HistoryFilled as HistoryFilledBase } from '@fluentui/react-icons/headless/svg/history';
import { GlobeRegular as GlobeRegularBase, GlobeFilled as GlobeFilledBase } from '@fluentui/react-icons/headless/svg/globe';
import { CloudRegular as CloudRegularBase, CloudFilled as CloudFilledBase } from '@fluentui/react-icons/headless/svg/cloud';
import { PhoneRegular as PhoneRegularBase, PhoneFilled as PhoneFilledBase } from '@fluentui/react-icons/headless/svg/phone';
import { DesktopRegular as DesktopRegularBase, DesktopFilled as DesktopFilledBase } from '@fluentui/react-icons/headless/svg/desktop';
import { WeatherMoonRegular as WeatherMoonRegularBase, WeatherMoonFilled as WeatherMoonFilledBase } from '@fluentui/react-icons/headless/svg/weather-moon';
import { WeatherSunnyRegular as WeatherSunnyRegularBase, WeatherSunnyFilled as WeatherSunnyFilledBase } from '@fluentui/react-icons/headless/svg/weather-sunny';

export const HomeRegular = wrapIcon(HomeRegularBase, 'HomeRegular');
export const HomeFilled = wrapIcon(HomeFilledBase, 'HomeFilled');
export const SettingsRegular = wrapIcon(SettingsRegularBase, 'SettingsRegular');
export const SettingsFilled = wrapIcon(SettingsFilledBase, 'SettingsFilled');
export const NavigationRegular = wrapIcon(NavigationRegularBase, 'NavigationRegular');
export const NavigationFilled = wrapIcon(NavigationFilledBase, 'NavigationFilled');
export const PanelLeftRegular = wrapIcon(PanelLeftRegularBase, 'PanelLeftRegular');
export const PanelLeftFilled = wrapIcon(PanelLeftFilledBase, 'PanelLeftFilled');
export const AppsRegular = wrapIcon(AppsRegularBase, 'AppsRegular');
export const AppsFilled = wrapIcon(AppsFilledBase, 'AppsFilled');
export const WindowRegular = wrapIcon(WindowRegularBase, 'WindowRegular');
export const WindowFilled = wrapIcon(WindowFilledBase, 'WindowFilled');
export const FullScreenMaximizeRegular = wrapIcon(FullScreenMaximizeRegularBase, 'FullScreenMaximizeRegular');
export const FullScreenMinimizeRegular = wrapIcon(FullScreenMinimizeRegularBase, 'FullScreenMinimizeRegular');
export const AddRegular = wrapIcon(AddRegularBase, 'AddRegular');
export const AddFilled = wrapIcon(AddFilledBase, 'AddFilled');
export const SubtractRegular = wrapIcon(SubtractRegularBase, 'SubtractRegular');
export const SubtractFilled = wrapIcon(SubtractFilledBase, 'SubtractFilled');
export const DismissRegular = wrapIcon(DismissRegularBase, 'DismissRegular');
export const DismissFilled = wrapIcon(DismissFilledBase, 'DismissFilled');
export const CheckmarkRegular = wrapIcon(CheckmarkRegularBase, 'CheckmarkRegular');
export const CheckmarkFilled = wrapIcon(CheckmarkFilledBase, 'CheckmarkFilled');
export const SearchRegular = wrapIcon(SearchRegularBase, 'SearchRegular');
export const SearchFilled = wrapIcon(SearchFilledBase, 'SearchFilled');
export const EditRegular = wrapIcon(EditRegularBase, 'EditRegular');
export const EditFilled = wrapIcon(EditFilledBase, 'EditFilled');
export const DeleteRegular = wrapIcon(DeleteRegularBase, 'DeleteRegular');
export const DeleteFilled = wrapIcon(DeleteFilledBase, 'DeleteFilled');
export const SaveRegular = wrapIcon(SaveRegularBase, 'SaveRegular');
export const SaveFilled = wrapIcon(SaveFilledBase, 'SaveFilled');
export const CopyRegular = wrapIcon(CopyRegularBase, 'CopyRegular');
export const CopyFilled = wrapIcon(CopyFilledBase, 'CopyFilled');
export const CutRegular = wrapIcon(CutRegularBase, 'CutRegular');
export const CutFilled = wrapIcon(CutFilledBase, 'CutFilled');
export const ClipboardRegular = wrapIcon(ClipboardRegularBase, 'ClipboardRegular');
export const ClipboardFilled = wrapIcon(ClipboardFilledBase, 'ClipboardFilled');
export const ShareRegular = wrapIcon(ShareRegularBase, 'ShareRegular');
export const ShareFilled = wrapIcon(ShareFilledBase, 'ShareFilled');
export const FilterRegular = wrapIcon(FilterRegularBase, 'FilterRegular');
export const FilterFilled = wrapIcon(FilterFilledBase, 'FilterFilled');
export const PrintRegular = wrapIcon(PrintRegularBase, 'PrintRegular');
export const PrintFilled = wrapIcon(PrintFilledBase, 'PrintFilled');
export const PinRegular = wrapIcon(PinRegularBase, 'PinRegular');
export const PinFilled = wrapIcon(PinFilledBase, 'PinFilled');
export const LinkRegular = wrapIcon(LinkRegularBase, 'LinkRegular');
export const LinkFilled = wrapIcon(LinkFilledBase, 'LinkFilled');
export const ChevronDownRegular = wrapIcon(ChevronDownRegularBase, 'ChevronDownRegular');
export const ChevronDownFilled = wrapIcon(ChevronDownFilledBase, 'ChevronDownFilled');
export const ChevronUpRegular = wrapIcon(ChevronUpRegularBase, 'ChevronUpRegular');
export const ChevronUpFilled = wrapIcon(ChevronUpFilledBase, 'ChevronUpFilled');
export const ChevronLeftRegular = wrapIcon(ChevronLeftRegularBase, 'ChevronLeftRegular');
export const ChevronLeftFilled = wrapIcon(ChevronLeftFilledBase, 'ChevronLeftFilled');
export const ChevronRightRegular = wrapIcon(ChevronRightRegularBase, 'ChevronRightRegular');
export const ChevronRightFilled = wrapIcon(ChevronRightFilledBase, 'ChevronRightFilled');
export const ArrowLeftRegular = wrapIcon(ArrowLeftRegularBase, 'ArrowLeftRegular');
export const ArrowLeftFilled = wrapIcon(ArrowLeftFilledBase, 'ArrowLeftFilled');
export const ArrowUpRegular = wrapIcon(ArrowUpRegularBase, 'ArrowUpRegular');
export const ArrowUpFilled = wrapIcon(ArrowUpFilledBase, 'ArrowUpFilled');
export const ArrowDownRegular = wrapIcon(ArrowDownRegularBase, 'ArrowDownRegular');
export const ArrowDownFilled = wrapIcon(ArrowDownFilledBase, 'ArrowDownFilled');
export const ArrowSortRegular = wrapIcon(ArrowSortRegularBase, 'ArrowSortRegular');
export const ArrowSortFilled = wrapIcon(ArrowSortFilledBase, 'ArrowSortFilled');
export const ArrowUploadRegular = wrapIcon(ArrowUploadRegularBase, 'ArrowUploadRegular');
export const ArrowUploadFilled = wrapIcon(ArrowUploadFilledBase, 'ArrowUploadFilled');
export const ArrowDownloadRegular = wrapIcon(ArrowDownloadRegularBase, 'ArrowDownloadRegular');
export const ArrowDownloadFilled = wrapIcon(ArrowDownloadFilledBase, 'ArrowDownloadFilled');
export const ArrowSyncRegular = wrapIcon(ArrowSyncRegularBase, 'ArrowSyncRegular');
export const ArrowSyncFilled = wrapIcon(ArrowSyncFilledBase, 'ArrowSyncFilled');
export const ArrowClockwiseRegular = wrapIcon(ArrowClockwiseRegularBase, 'ArrowClockwiseRegular');
export const ArrowClockwiseFilled = wrapIcon(ArrowClockwiseFilledBase, 'ArrowClockwiseFilled');
export const InfoRegular = wrapIcon(InfoRegularBase, 'InfoRegular');
export const InfoFilled = wrapIcon(InfoFilledBase, 'InfoFilled');
export const CheckmarkCircleRegular = wrapIcon(CheckmarkCircleRegularBase, 'CheckmarkCircleRegular');
export const CheckmarkCircleFilled = wrapIcon(CheckmarkCircleFilledBase, 'CheckmarkCircleFilled');
export const WarningRegular = wrapIcon(WarningRegularBase, 'WarningRegular');
export const WarningFilled = wrapIcon(WarningFilledBase, 'WarningFilled');
export const ErrorCircleRegular = wrapIcon(ErrorCircleRegularBase, 'ErrorCircleRegular');
export const ErrorCircleFilled = wrapIcon(ErrorCircleFilledBase, 'ErrorCircleFilled');
export const QuestionCircleRegular = wrapIcon(QuestionCircleRegularBase, 'QuestionCircleRegular');
export const QuestionCircleFilled = wrapIcon(QuestionCircleFilledBase, 'QuestionCircleFilled');
export const AlertRegular = wrapIcon(AlertRegularBase, 'AlertRegular');
export const AlertFilled = wrapIcon(AlertFilledBase, 'AlertFilled');
export const ImageRegular = wrapIcon(ImageRegularBase, 'ImageRegular');
export const ImageFilled = wrapIcon(ImageFilledBase, 'ImageFilled');
export const DocumentRegular = wrapIcon(DocumentRegularBase, 'DocumentRegular');
export const DocumentFilled = wrapIcon(DocumentFilledBase, 'DocumentFilled');
export const FolderRegular = wrapIcon(FolderRegularBase, 'FolderRegular');
export const FolderFilled = wrapIcon(FolderFilledBase, 'FolderFilled');
export const FolderOpenRegular = wrapIcon(FolderOpenRegularBase, 'FolderOpenRegular');
export const FolderOpenFilled = wrapIcon(FolderOpenFilledBase, 'FolderOpenFilled');
export const EyeRegular = wrapIcon(EyeRegularBase, 'EyeRegular');
export const EyeFilled = wrapIcon(EyeFilledBase, 'EyeFilled');
export const EyeOffRegular = wrapIcon(EyeOffRegularBase, 'EyeOffRegular');
export const EyeOffFilled = wrapIcon(EyeOffFilledBase, 'EyeOffFilled');
export const ZoomInRegular = wrapIcon(ZoomInRegularBase, 'ZoomInRegular');
export const ZoomInFilled = wrapIcon(ZoomInFilledBase, 'ZoomInFilled');
export const ZoomOutRegular = wrapIcon(ZoomOutRegularBase, 'ZoomOutRegular');
export const ZoomOutFilled = wrapIcon(ZoomOutFilledBase, 'ZoomOutFilled');
export const PlayRegular = wrapIcon(PlayRegularBase, 'PlayRegular');
export const PlayFilled = wrapIcon(PlayFilledBase, 'PlayFilled');
export const PauseRegular = wrapIcon(PauseRegularBase, 'PauseRegular');
export const PauseFilled = wrapIcon(PauseFilledBase, 'PauseFilled');
export const MoreHorizontalRegular = wrapIcon(MoreHorizontalRegularBase, 'MoreHorizontalRegular');
export const MoreHorizontalFilled = wrapIcon(MoreHorizontalFilledBase, 'MoreHorizontalFilled');
export const OptionsRegular = wrapIcon(OptionsRegularBase, 'OptionsRegular');
export const OptionsFilled = wrapIcon(OptionsFilledBase, 'OptionsFilled');
export const CalendarLtrRegular = wrapIcon(CalendarLtrRegularBase, 'CalendarLtrRegular');
export const CalendarLtrFilled = wrapIcon(CalendarLtrFilledBase, 'CalendarLtrFilled');
export const GridRegular = wrapIcon(GridRegularBase, 'GridRegular');
export const GridFilled = wrapIcon(GridFilledBase, 'GridFilled');
export const ListRegular = wrapIcon(ListRegularBase, 'ListRegular');
export const ListFilled = wrapIcon(ListFilledBase, 'ListFilled');
export const TableRegular = wrapIcon(TableRegularBase, 'TableRegular');
export const TableFilled = wrapIcon(TableFilledBase, 'TableFilled');
export const ChatRegular = wrapIcon(ChatRegularBase, 'ChatRegular');
export const ChatFilled = wrapIcon(ChatFilledBase, 'ChatFilled');
export const MailRegular = wrapIcon(MailRegularBase, 'MailRegular');
export const MailFilled = wrapIcon(MailFilledBase, 'MailFilled');
export const PersonRegular = wrapIcon(PersonRegularBase, 'PersonRegular');
export const PersonFilled = wrapIcon(PersonFilledBase, 'PersonFilled');
export const TagRegular = wrapIcon(TagRegularBase, 'TagRegular');
export const TagFilled = wrapIcon(TagFilledBase, 'TagFilled');
export const BookmarkRegular = wrapIcon(BookmarkRegularBase, 'BookmarkRegular');
export const BookmarkFilled = wrapIcon(BookmarkFilledBase, 'BookmarkFilled');
export const FlagRegular = wrapIcon(FlagRegularBase, 'FlagRegular');
export const FlagFilled = wrapIcon(FlagFilledBase, 'FlagFilled');
export const StarRegular = wrapIcon(StarRegularBase, 'StarRegular');
export const StarFilled = wrapIcon(StarFilledBase, 'StarFilled');
export const HeartRegular = wrapIcon(HeartRegularBase, 'HeartRegular');
export const HeartFilled = wrapIcon(HeartFilledBase, 'HeartFilled');
export const LockClosedRegular = wrapIcon(LockClosedRegularBase, 'LockClosedRegular');
export const LockClosedFilled = wrapIcon(LockClosedFilledBase, 'LockClosedFilled');
export const ColorRegular = wrapIcon(ColorRegularBase, 'ColorRegular');
export const ColorFilled = wrapIcon(ColorFilledBase, 'ColorFilled');
export const PaintBrushRegular = wrapIcon(PaintBrushRegularBase, 'PaintBrushRegular');
export const PaintBrushFilled = wrapIcon(PaintBrushFilledBase, 'PaintBrushFilled');
export const TextFontRegular = wrapIcon(TextFontRegularBase, 'TextFontRegular');
export const TextFontFilled = wrapIcon(TextFontFilledBase, 'TextFontFilled');
export const KeyboardRegular = wrapIcon(KeyboardRegularBase, 'KeyboardRegular');
export const KeyboardFilled = wrapIcon(KeyboardFilledBase, 'KeyboardFilled');
export const CodeRegular = wrapIcon(CodeRegularBase, 'CodeRegular');
export const CodeFilled = wrapIcon(CodeFilledBase, 'CodeFilled');
export const StackRegular = wrapIcon(StackRegularBase, 'StackRegular');
export const StackFilled = wrapIcon(StackFilledBase, 'StackFilled');
export const CompassNorthwestRegular = wrapIcon(CompassNorthwestRegularBase, 'CompassNorthwestRegular');
export const CompassNorthwestFilled = wrapIcon(CompassNorthwestFilledBase, 'CompassNorthwestFilled');
export const MaximizeRegular = wrapIcon(MaximizeRegularBase, 'MaximizeRegular');
export const MaximizeFilled = wrapIcon(MaximizeFilledBase, 'MaximizeFilled');
export const SquareMultipleRegular = wrapIcon(SquareMultipleRegularBase, 'SquareMultipleRegular');
export const SquareMultipleFilled = wrapIcon(SquareMultipleFilledBase, 'SquareMultipleFilled');
export const ClockRegular = wrapIcon(ClockRegularBase, 'ClockRegular');
export const ClockFilled = wrapIcon(ClockFilledBase, 'ClockFilled');
export const HistoryRegular = wrapIcon(HistoryRegularBase, 'HistoryRegular');
export const HistoryFilled = wrapIcon(HistoryFilledBase, 'HistoryFilled');
export const GlobeRegular = wrapIcon(GlobeRegularBase, 'GlobeRegular');
export const GlobeFilled = wrapIcon(GlobeFilledBase, 'GlobeFilled');
export const CloudRegular = wrapIcon(CloudRegularBase, 'CloudRegular');
export const CloudFilled = wrapIcon(CloudFilledBase, 'CloudFilled');
export const PhoneRegular = wrapIcon(PhoneRegularBase, 'PhoneRegular');
export const PhoneFilled = wrapIcon(PhoneFilledBase, 'PhoneFilled');
export const DesktopRegular = wrapIcon(DesktopRegularBase, 'DesktopRegular');
export const DesktopFilled = wrapIcon(DesktopFilledBase, 'DesktopFilled');
export const WeatherMoonRegular = wrapIcon(WeatherMoonRegularBase, 'WeatherMoonRegular');
export const WeatherMoonFilled = wrapIcon(WeatherMoonFilledBase, 'WeatherMoonFilled');
export const WeatherSunnyRegular = wrapIcon(WeatherSunnyRegularBase, 'WeatherSunnyRegular');
export const WeatherSunnyFilled = wrapIcon(WeatherSunnyFilledBase, 'WeatherSunnyFilled');
