/* 自动生成:node scripts/gen-icon-package.mjs —— 勿手改 */
import { wrapIcon } from './wrap';
import { HomeRegular as HomeRegularBase, HomeFilled as HomeFilledBase } from '@fluentui/react-icons/headless/svg/home';
import { SettingsRegular as SettingsRegularBase, SettingsFilled as SettingsFilledBase } from '@fluentui/react-icons/headless/svg/settings';
import { NavigationRegular as NavigationRegularBase, NavigationFilled as NavigationFilledBase } from '@fluentui/react-icons/headless/svg/navigation';
import { PanelLeftRegular as PanelLeftRegularBase, PanelLeftFilled as PanelLeftFilledBase } from '@fluentui/react-icons/headless/svg/panel-left';
import { AppsRegular as AppsRegularBase, AppsFilled as AppsFilledBase } from '@fluentui/react-icons/headless/svg/apps';
import { WindowRegular as WindowRegularBase, WindowFilled as WindowFilledBase } from '@fluentui/react-icons/headless/svg/window';
import { FullScreenMaximizeRegular as FullScreenMaximizeRegularBase } from '@fluentui/react-icons/headless/svg/full-screen-maximize';
import { FullScreenMinimizeRegular as FullScreenMinimizeRegularBase } from '@fluentui/react-icons/headless/svg/full-screen-minimize';
import { AddRegular as AddRegularBase, AddFilled as AddFilledBase } from '@fluentui/react-icons/headless/svg/add';
import { SubtractRegular as SubtractRegularBase, SubtractFilled as SubtractFilledBase } from '@fluentui/react-icons/headless/svg/subtract';
import { DismissRegular as DismissRegularBase, DismissFilled as DismissFilledBase } from '@fluentui/react-icons/headless/svg/dismiss';
import { CheckmarkRegular as CheckmarkRegularBase, CheckmarkFilled as CheckmarkFilledBase } from '@fluentui/react-icons/headless/svg/checkmark';
import { SearchRegular as SearchRegularBase, SearchFilled as SearchFilledBase } from '@fluentui/react-icons/headless/svg/search';
import { EditRegular as EditRegularBase, EditFilled as EditFilledBase } from '@fluentui/react-icons/headless/svg/edit';
import { DeleteRegular as DeleteRegularBase, DeleteFilled as DeleteFilledBase } from '@fluentui/react-icons/headless/svg/delete';
import { SaveRegular as SaveRegularBase, SaveFilled as SaveFilledBase } from '@fluentui/react-icons/headless/svg/save';
import { CopyRegular as CopyRegularBase, CopyFilled as CopyFilledBase } from '@fluentui/react-icons/headless/svg/copy';
import { CutRegular as CutRegularBase, CutFilled as CutFilledBase } from '@fluentui/react-icons/headless/svg/cut';
import { ClipboardRegular as ClipboardRegularBase, ClipboardFilled as ClipboardFilledBase } from '@fluentui/react-icons/headless/svg/clipboard';
import { ShareRegular as ShareRegularBase, ShareFilled as ShareFilledBase } from '@fluentui/react-icons/headless/svg/share';
import { FilterRegular as FilterRegularBase, FilterFilled as FilterFilledBase } from '@fluentui/react-icons/headless/svg/filter';
import { PrintRegular as PrintRegularBase, PrintFilled as PrintFilledBase } from '@fluentui/react-icons/headless/svg/print';
import { PinRegular as PinRegularBase, PinFilled as PinFilledBase } from '@fluentui/react-icons/headless/svg/pin';
import { LinkRegular as LinkRegularBase, LinkFilled as LinkFilledBase } from '@fluentui/react-icons/headless/svg/link';
import { ChevronDownRegular as ChevronDownRegularBase, ChevronDownFilled as ChevronDownFilledBase } from '@fluentui/react-icons/headless/svg/chevron-down';
import { ChevronUpRegular as ChevronUpRegularBase, ChevronUpFilled as ChevronUpFilledBase } from '@fluentui/react-icons/headless/svg/chevron-up';
import { ChevronLeftRegular as ChevronLeftRegularBase, ChevronLeftFilled as ChevronLeftFilledBase } from '@fluentui/react-icons/headless/svg/chevron-left';
import { ChevronRightRegular as ChevronRightRegularBase, ChevronRightFilled as ChevronRightFilledBase } from '@fluentui/react-icons/headless/svg/chevron-right';
import { ArrowLeftRegular as ArrowLeftRegularBase, ArrowLeftFilled as ArrowLeftFilledBase } from '@fluentui/react-icons/headless/svg/arrow-left';
import { ArrowUpRegular as ArrowUpRegularBase, ArrowUpFilled as ArrowUpFilledBase } from '@fluentui/react-icons/headless/svg/arrow-up';
import { ArrowDownRegular as ArrowDownRegularBase, ArrowDownFilled as ArrowDownFilledBase } from '@fluentui/react-icons/headless/svg/arrow-down';
import { ArrowSortRegular as ArrowSortRegularBase, ArrowSortFilled as ArrowSortFilledBase } from '@fluentui/react-icons/headless/svg/arrow-sort';
import { ArrowUploadRegular as ArrowUploadRegularBase, ArrowUploadFilled as ArrowUploadFilledBase } from '@fluentui/react-icons/headless/svg/arrow-upload';
import { ArrowDownloadRegular as ArrowDownloadRegularBase, ArrowDownloadFilled as ArrowDownloadFilledBase } from '@fluentui/react-icons/headless/svg/arrow-download';
import { ArrowSyncRegular as ArrowSyncRegularBase, ArrowSyncFilled as ArrowSyncFilledBase } from '@fluentui/react-icons/headless/svg/arrow-sync';
import { ArrowClockwiseRegular as ArrowClockwiseRegularBase, ArrowClockwiseFilled as ArrowClockwiseFilledBase } from '@fluentui/react-icons/headless/svg/arrow-clockwise';
import { InfoRegular as InfoRegularBase, InfoFilled as InfoFilledBase } from '@fluentui/react-icons/headless/svg/info';
import { CheckmarkCircleRegular as CheckmarkCircleRegularBase, CheckmarkCircleFilled as CheckmarkCircleFilledBase } from '@fluentui/react-icons/headless/svg/checkmark-circle';
import { WarningRegular as WarningRegularBase, WarningFilled as WarningFilledBase } from '@fluentui/react-icons/headless/svg/warning';
import { ErrorCircleRegular as ErrorCircleRegularBase, ErrorCircleFilled as ErrorCircleFilledBase } from '@fluentui/react-icons/headless/svg/error-circle';
import { QuestionCircleRegular as QuestionCircleRegularBase, QuestionCircleFilled as QuestionCircleFilledBase } from '@fluentui/react-icons/headless/svg/question-circle';
import { AlertRegular as AlertRegularBase, AlertFilled as AlertFilledBase } from '@fluentui/react-icons/headless/svg/alert';
import { ImageRegular as ImageRegularBase, ImageFilled as ImageFilledBase } from '@fluentui/react-icons/headless/svg/image';
import { DocumentRegular as DocumentRegularBase, DocumentFilled as DocumentFilledBase } from '@fluentui/react-icons/headless/svg/document';
import { FolderRegular as FolderRegularBase, FolderFilled as FolderFilledBase } from '@fluentui/react-icons/headless/svg/folder';
import { FolderOpenRegular as FolderOpenRegularBase, FolderOpenFilled as FolderOpenFilledBase } from '@fluentui/react-icons/headless/svg/folder-open';
import { EyeRegular as EyeRegularBase, EyeFilled as EyeFilledBase } from '@fluentui/react-icons/headless/svg/eye';
import { EyeOffRegular as EyeOffRegularBase, EyeOffFilled as EyeOffFilledBase } from '@fluentui/react-icons/headless/svg/eye-off';
import { ZoomInRegular as ZoomInRegularBase, ZoomInFilled as ZoomInFilledBase } from '@fluentui/react-icons/headless/svg/zoom-in';
import { ZoomOutRegular as ZoomOutRegularBase, ZoomOutFilled as ZoomOutFilledBase } from '@fluentui/react-icons/headless/svg/zoom-out';
import { PlayRegular as PlayRegularBase, PlayFilled as PlayFilledBase } from '@fluentui/react-icons/headless/svg/play';
import { PauseRegular as PauseRegularBase, PauseFilled as PauseFilledBase } from '@fluentui/react-icons/headless/svg/pause';
import { MoreHorizontalRegular as MoreHorizontalRegularBase, MoreHorizontalFilled as MoreHorizontalFilledBase } from '@fluentui/react-icons/headless/svg/more-horizontal';
import { OptionsRegular as OptionsRegularBase, OptionsFilled as OptionsFilledBase } from '@fluentui/react-icons/headless/svg/options';
import { CalendarLtrRegular as CalendarLtrRegularBase, CalendarLtrFilled as CalendarLtrFilledBase } from '@fluentui/react-icons/headless/svg/calendar-ltr';
import { GridRegular as GridRegularBase, GridFilled as GridFilledBase } from '@fluentui/react-icons/headless/svg/grid';
import { ListRegular as ListRegularBase, ListFilled as ListFilledBase } from '@fluentui/react-icons/headless/svg/list';
import { TableRegular as TableRegularBase, TableFilled as TableFilledBase } from '@fluentui/react-icons/headless/svg/table';
import { ChatRegular as ChatRegularBase, ChatFilled as ChatFilledBase } from '@fluentui/react-icons/headless/svg/chat';
import { MailRegular as MailRegularBase, MailFilled as MailFilledBase } from '@fluentui/react-icons/headless/svg/mail';
import { PersonRegular as PersonRegularBase, PersonFilled as PersonFilledBase } from '@fluentui/react-icons/headless/svg/person';
import { TagRegular as TagRegularBase, TagFilled as TagFilledBase } from '@fluentui/react-icons/headless/svg/tag';
import { BookmarkRegular as BookmarkRegularBase, BookmarkFilled as BookmarkFilledBase } from '@fluentui/react-icons/headless/svg/bookmark';
import { FlagRegular as FlagRegularBase, FlagFilled as FlagFilledBase } from '@fluentui/react-icons/headless/svg/flag';
import { StarRegular as StarRegularBase, StarFilled as StarFilledBase } from '@fluentui/react-icons/headless/svg/star';
import { HeartRegular as HeartRegularBase, HeartFilled as HeartFilledBase } from '@fluentui/react-icons/headless/svg/heart';
import { LockClosedRegular as LockClosedRegularBase, LockClosedFilled as LockClosedFilledBase } from '@fluentui/react-icons/headless/svg/lock-closed';
import { ColorRegular as ColorRegularBase, ColorFilled as ColorFilledBase } from '@fluentui/react-icons/headless/svg/color';
import { PaintBrushRegular as PaintBrushRegularBase, PaintBrushFilled as PaintBrushFilledBase } from '@fluentui/react-icons/headless/svg/paint-brush';
import { TextFontRegular as TextFontRegularBase, TextFontFilled as TextFontFilledBase } from '@fluentui/react-icons/headless/svg/text-font';
import { KeyboardRegular as KeyboardRegularBase, KeyboardFilled as KeyboardFilledBase } from '@fluentui/react-icons/headless/svg/keyboard';
import { CodeRegular as CodeRegularBase, CodeFilled as CodeFilledBase } from '@fluentui/react-icons/headless/svg/code';
import { StackRegular as StackRegularBase, StackFilled as StackFilledBase } from '@fluentui/react-icons/headless/svg/stack';
import { CompassNorthwestRegular as CompassNorthwestRegularBase, CompassNorthwestFilled as CompassNorthwestFilledBase } from '@fluentui/react-icons/headless/svg/compass-northwest';
import { MaximizeRegular as MaximizeRegularBase, MaximizeFilled as MaximizeFilledBase } from '@fluentui/react-icons/headless/svg/maximize';
import { SquareMultipleRegular as SquareMultipleRegularBase, SquareMultipleFilled as SquareMultipleFilledBase } from '@fluentui/react-icons/headless/svg/square-multiple';
import { ClockRegular as ClockRegularBase, ClockFilled as ClockFilledBase } from '@fluentui/react-icons/headless/svg/clock';
import { HistoryRegular as HistoryRegularBase, HistoryFilled as HistoryFilledBase } from '@fluentui/react-icons/headless/svg/history';
import { GlobeRegular as GlobeRegularBase, GlobeFilled as GlobeFilledBase } from '@fluentui/react-icons/headless/svg/globe';
import { CloudRegular as CloudRegularBase, CloudFilled as CloudFilledBase } from '@fluentui/react-icons/headless/svg/cloud';
import { PhoneRegular as PhoneRegularBase, PhoneFilled as PhoneFilledBase } from '@fluentui/react-icons/headless/svg/phone';
import { DesktopRegular as DesktopRegularBase, DesktopFilled as DesktopFilledBase } from '@fluentui/react-icons/headless/svg/desktop';
import { WeatherMoonRegular as WeatherMoonRegularBase, WeatherMoonFilled as WeatherMoonFilledBase } from '@fluentui/react-icons/headless/svg/weather-moon';
import { WeatherSunnyRegular as WeatherSunnyRegularBase, WeatherSunnyFilled as WeatherSunnyFilledBase } from '@fluentui/react-icons/headless/svg/weather-sunny';

export const HomeRegular = /*#__PURE__*/ wrapIcon(HomeRegularBase, 'HomeRegular');
export const HomeFilled = /*#__PURE__*/ wrapIcon(HomeFilledBase, 'HomeFilled');
export const SettingsRegular = /*#__PURE__*/ wrapIcon(SettingsRegularBase, 'SettingsRegular');
export const SettingsFilled = /*#__PURE__*/ wrapIcon(SettingsFilledBase, 'SettingsFilled');
export const NavigationRegular = /*#__PURE__*/ wrapIcon(NavigationRegularBase, 'NavigationRegular');
export const NavigationFilled = /*#__PURE__*/ wrapIcon(NavigationFilledBase, 'NavigationFilled');
export const PanelLeftRegular = /*#__PURE__*/ wrapIcon(PanelLeftRegularBase, 'PanelLeftRegular');
export const PanelLeftFilled = /*#__PURE__*/ wrapIcon(PanelLeftFilledBase, 'PanelLeftFilled');
export const AppsRegular = /*#__PURE__*/ wrapIcon(AppsRegularBase, 'AppsRegular');
export const AppsFilled = /*#__PURE__*/ wrapIcon(AppsFilledBase, 'AppsFilled');
export const WindowRegular = /*#__PURE__*/ wrapIcon(WindowRegularBase, 'WindowRegular');
export const WindowFilled = /*#__PURE__*/ wrapIcon(WindowFilledBase, 'WindowFilled');
export const FullScreenMaximizeRegular = /*#__PURE__*/ wrapIcon(FullScreenMaximizeRegularBase, 'FullScreenMaximizeRegular');
export const FullScreenMinimizeRegular = /*#__PURE__*/ wrapIcon(FullScreenMinimizeRegularBase, 'FullScreenMinimizeRegular');
export const AddRegular = /*#__PURE__*/ wrapIcon(AddRegularBase, 'AddRegular');
export const AddFilled = /*#__PURE__*/ wrapIcon(AddFilledBase, 'AddFilled');
export const SubtractRegular = /*#__PURE__*/ wrapIcon(SubtractRegularBase, 'SubtractRegular');
export const SubtractFilled = /*#__PURE__*/ wrapIcon(SubtractFilledBase, 'SubtractFilled');
export const DismissRegular = /*#__PURE__*/ wrapIcon(DismissRegularBase, 'DismissRegular');
export const DismissFilled = /*#__PURE__*/ wrapIcon(DismissFilledBase, 'DismissFilled');
export const CheckmarkRegular = /*#__PURE__*/ wrapIcon(CheckmarkRegularBase, 'CheckmarkRegular');
export const CheckmarkFilled = /*#__PURE__*/ wrapIcon(CheckmarkFilledBase, 'CheckmarkFilled');
export const SearchRegular = /*#__PURE__*/ wrapIcon(SearchRegularBase, 'SearchRegular');
export const SearchFilled = /*#__PURE__*/ wrapIcon(SearchFilledBase, 'SearchFilled');
export const EditRegular = /*#__PURE__*/ wrapIcon(EditRegularBase, 'EditRegular');
export const EditFilled = /*#__PURE__*/ wrapIcon(EditFilledBase, 'EditFilled');
export const DeleteRegular = /*#__PURE__*/ wrapIcon(DeleteRegularBase, 'DeleteRegular');
export const DeleteFilled = /*#__PURE__*/ wrapIcon(DeleteFilledBase, 'DeleteFilled');
export const SaveRegular = /*#__PURE__*/ wrapIcon(SaveRegularBase, 'SaveRegular');
export const SaveFilled = /*#__PURE__*/ wrapIcon(SaveFilledBase, 'SaveFilled');
export const CopyRegular = /*#__PURE__*/ wrapIcon(CopyRegularBase, 'CopyRegular');
export const CopyFilled = /*#__PURE__*/ wrapIcon(CopyFilledBase, 'CopyFilled');
export const CutRegular = /*#__PURE__*/ wrapIcon(CutRegularBase, 'CutRegular');
export const CutFilled = /*#__PURE__*/ wrapIcon(CutFilledBase, 'CutFilled');
export const ClipboardRegular = /*#__PURE__*/ wrapIcon(ClipboardRegularBase, 'ClipboardRegular');
export const ClipboardFilled = /*#__PURE__*/ wrapIcon(ClipboardFilledBase, 'ClipboardFilled');
export const ShareRegular = /*#__PURE__*/ wrapIcon(ShareRegularBase, 'ShareRegular');
export const ShareFilled = /*#__PURE__*/ wrapIcon(ShareFilledBase, 'ShareFilled');
export const FilterRegular = /*#__PURE__*/ wrapIcon(FilterRegularBase, 'FilterRegular');
export const FilterFilled = /*#__PURE__*/ wrapIcon(FilterFilledBase, 'FilterFilled');
export const PrintRegular = /*#__PURE__*/ wrapIcon(PrintRegularBase, 'PrintRegular');
export const PrintFilled = /*#__PURE__*/ wrapIcon(PrintFilledBase, 'PrintFilled');
export const PinRegular = /*#__PURE__*/ wrapIcon(PinRegularBase, 'PinRegular');
export const PinFilled = /*#__PURE__*/ wrapIcon(PinFilledBase, 'PinFilled');
export const LinkRegular = /*#__PURE__*/ wrapIcon(LinkRegularBase, 'LinkRegular');
export const LinkFilled = /*#__PURE__*/ wrapIcon(LinkFilledBase, 'LinkFilled');
export const ChevronDownRegular = /*#__PURE__*/ wrapIcon(ChevronDownRegularBase, 'ChevronDownRegular');
export const ChevronDownFilled = /*#__PURE__*/ wrapIcon(ChevronDownFilledBase, 'ChevronDownFilled');
export const ChevronUpRegular = /*#__PURE__*/ wrapIcon(ChevronUpRegularBase, 'ChevronUpRegular');
export const ChevronUpFilled = /*#__PURE__*/ wrapIcon(ChevronUpFilledBase, 'ChevronUpFilled');
export const ChevronLeftRegular = /*#__PURE__*/ wrapIcon(ChevronLeftRegularBase, 'ChevronLeftRegular');
export const ChevronLeftFilled = /*#__PURE__*/ wrapIcon(ChevronLeftFilledBase, 'ChevronLeftFilled');
export const ChevronRightRegular = /*#__PURE__*/ wrapIcon(ChevronRightRegularBase, 'ChevronRightRegular');
export const ChevronRightFilled = /*#__PURE__*/ wrapIcon(ChevronRightFilledBase, 'ChevronRightFilled');
export const ArrowLeftRegular = /*#__PURE__*/ wrapIcon(ArrowLeftRegularBase, 'ArrowLeftRegular');
export const ArrowLeftFilled = /*#__PURE__*/ wrapIcon(ArrowLeftFilledBase, 'ArrowLeftFilled');
export const ArrowUpRegular = /*#__PURE__*/ wrapIcon(ArrowUpRegularBase, 'ArrowUpRegular');
export const ArrowUpFilled = /*#__PURE__*/ wrapIcon(ArrowUpFilledBase, 'ArrowUpFilled');
export const ArrowDownRegular = /*#__PURE__*/ wrapIcon(ArrowDownRegularBase, 'ArrowDownRegular');
export const ArrowDownFilled = /*#__PURE__*/ wrapIcon(ArrowDownFilledBase, 'ArrowDownFilled');
export const ArrowSortRegular = /*#__PURE__*/ wrapIcon(ArrowSortRegularBase, 'ArrowSortRegular');
export const ArrowSortFilled = /*#__PURE__*/ wrapIcon(ArrowSortFilledBase, 'ArrowSortFilled');
export const ArrowUploadRegular = /*#__PURE__*/ wrapIcon(ArrowUploadRegularBase, 'ArrowUploadRegular');
export const ArrowUploadFilled = /*#__PURE__*/ wrapIcon(ArrowUploadFilledBase, 'ArrowUploadFilled');
export const ArrowDownloadRegular = /*#__PURE__*/ wrapIcon(ArrowDownloadRegularBase, 'ArrowDownloadRegular');
export const ArrowDownloadFilled = /*#__PURE__*/ wrapIcon(ArrowDownloadFilledBase, 'ArrowDownloadFilled');
export const ArrowSyncRegular = /*#__PURE__*/ wrapIcon(ArrowSyncRegularBase, 'ArrowSyncRegular');
export const ArrowSyncFilled = /*#__PURE__*/ wrapIcon(ArrowSyncFilledBase, 'ArrowSyncFilled');
export const ArrowClockwiseRegular = /*#__PURE__*/ wrapIcon(ArrowClockwiseRegularBase, 'ArrowClockwiseRegular');
export const ArrowClockwiseFilled = /*#__PURE__*/ wrapIcon(ArrowClockwiseFilledBase, 'ArrowClockwiseFilled');
export const InfoRegular = /*#__PURE__*/ wrapIcon(InfoRegularBase, 'InfoRegular');
export const InfoFilled = /*#__PURE__*/ wrapIcon(InfoFilledBase, 'InfoFilled');
export const CheckmarkCircleRegular = /*#__PURE__*/ wrapIcon(CheckmarkCircleRegularBase, 'CheckmarkCircleRegular');
export const CheckmarkCircleFilled = /*#__PURE__*/ wrapIcon(CheckmarkCircleFilledBase, 'CheckmarkCircleFilled');
export const WarningRegular = /*#__PURE__*/ wrapIcon(WarningRegularBase, 'WarningRegular');
export const WarningFilled = /*#__PURE__*/ wrapIcon(WarningFilledBase, 'WarningFilled');
export const ErrorCircleRegular = /*#__PURE__*/ wrapIcon(ErrorCircleRegularBase, 'ErrorCircleRegular');
export const ErrorCircleFilled = /*#__PURE__*/ wrapIcon(ErrorCircleFilledBase, 'ErrorCircleFilled');
export const QuestionCircleRegular = /*#__PURE__*/ wrapIcon(QuestionCircleRegularBase, 'QuestionCircleRegular');
export const QuestionCircleFilled = /*#__PURE__*/ wrapIcon(QuestionCircleFilledBase, 'QuestionCircleFilled');
export const AlertRegular = /*#__PURE__*/ wrapIcon(AlertRegularBase, 'AlertRegular');
export const AlertFilled = /*#__PURE__*/ wrapIcon(AlertFilledBase, 'AlertFilled');
export const ImageRegular = /*#__PURE__*/ wrapIcon(ImageRegularBase, 'ImageRegular');
export const ImageFilled = /*#__PURE__*/ wrapIcon(ImageFilledBase, 'ImageFilled');
export const DocumentRegular = /*#__PURE__*/ wrapIcon(DocumentRegularBase, 'DocumentRegular');
export const DocumentFilled = /*#__PURE__*/ wrapIcon(DocumentFilledBase, 'DocumentFilled');
export const FolderRegular = /*#__PURE__*/ wrapIcon(FolderRegularBase, 'FolderRegular');
export const FolderFilled = /*#__PURE__*/ wrapIcon(FolderFilledBase, 'FolderFilled');
export const FolderOpenRegular = /*#__PURE__*/ wrapIcon(FolderOpenRegularBase, 'FolderOpenRegular');
export const FolderOpenFilled = /*#__PURE__*/ wrapIcon(FolderOpenFilledBase, 'FolderOpenFilled');
export const EyeRegular = /*#__PURE__*/ wrapIcon(EyeRegularBase, 'EyeRegular');
export const EyeFilled = /*#__PURE__*/ wrapIcon(EyeFilledBase, 'EyeFilled');
export const EyeOffRegular = /*#__PURE__*/ wrapIcon(EyeOffRegularBase, 'EyeOffRegular');
export const EyeOffFilled = /*#__PURE__*/ wrapIcon(EyeOffFilledBase, 'EyeOffFilled');
export const ZoomInRegular = /*#__PURE__*/ wrapIcon(ZoomInRegularBase, 'ZoomInRegular');
export const ZoomInFilled = /*#__PURE__*/ wrapIcon(ZoomInFilledBase, 'ZoomInFilled');
export const ZoomOutRegular = /*#__PURE__*/ wrapIcon(ZoomOutRegularBase, 'ZoomOutRegular');
export const ZoomOutFilled = /*#__PURE__*/ wrapIcon(ZoomOutFilledBase, 'ZoomOutFilled');
export const PlayRegular = /*#__PURE__*/ wrapIcon(PlayRegularBase, 'PlayRegular');
export const PlayFilled = /*#__PURE__*/ wrapIcon(PlayFilledBase, 'PlayFilled');
export const PauseRegular = /*#__PURE__*/ wrapIcon(PauseRegularBase, 'PauseRegular');
export const PauseFilled = /*#__PURE__*/ wrapIcon(PauseFilledBase, 'PauseFilled');
export const MoreHorizontalRegular = /*#__PURE__*/ wrapIcon(MoreHorizontalRegularBase, 'MoreHorizontalRegular');
export const MoreHorizontalFilled = /*#__PURE__*/ wrapIcon(MoreHorizontalFilledBase, 'MoreHorizontalFilled');
export const OptionsRegular = /*#__PURE__*/ wrapIcon(OptionsRegularBase, 'OptionsRegular');
export const OptionsFilled = /*#__PURE__*/ wrapIcon(OptionsFilledBase, 'OptionsFilled');
export const CalendarLtrRegular = /*#__PURE__*/ wrapIcon(CalendarLtrRegularBase, 'CalendarLtrRegular');
export const CalendarLtrFilled = /*#__PURE__*/ wrapIcon(CalendarLtrFilledBase, 'CalendarLtrFilled');
export const GridRegular = /*#__PURE__*/ wrapIcon(GridRegularBase, 'GridRegular');
export const GridFilled = /*#__PURE__*/ wrapIcon(GridFilledBase, 'GridFilled');
export const ListRegular = /*#__PURE__*/ wrapIcon(ListRegularBase, 'ListRegular');
export const ListFilled = /*#__PURE__*/ wrapIcon(ListFilledBase, 'ListFilled');
export const TableRegular = /*#__PURE__*/ wrapIcon(TableRegularBase, 'TableRegular');
export const TableFilled = /*#__PURE__*/ wrapIcon(TableFilledBase, 'TableFilled');
export const ChatRegular = /*#__PURE__*/ wrapIcon(ChatRegularBase, 'ChatRegular');
export const ChatFilled = /*#__PURE__*/ wrapIcon(ChatFilledBase, 'ChatFilled');
export const MailRegular = /*#__PURE__*/ wrapIcon(MailRegularBase, 'MailRegular');
export const MailFilled = /*#__PURE__*/ wrapIcon(MailFilledBase, 'MailFilled');
export const PersonRegular = /*#__PURE__*/ wrapIcon(PersonRegularBase, 'PersonRegular');
export const PersonFilled = /*#__PURE__*/ wrapIcon(PersonFilledBase, 'PersonFilled');
export const TagRegular = /*#__PURE__*/ wrapIcon(TagRegularBase, 'TagRegular');
export const TagFilled = /*#__PURE__*/ wrapIcon(TagFilledBase, 'TagFilled');
export const BookmarkRegular = /*#__PURE__*/ wrapIcon(BookmarkRegularBase, 'BookmarkRegular');
export const BookmarkFilled = /*#__PURE__*/ wrapIcon(BookmarkFilledBase, 'BookmarkFilled');
export const FlagRegular = /*#__PURE__*/ wrapIcon(FlagRegularBase, 'FlagRegular');
export const FlagFilled = /*#__PURE__*/ wrapIcon(FlagFilledBase, 'FlagFilled');
export const StarRegular = /*#__PURE__*/ wrapIcon(StarRegularBase, 'StarRegular');
export const StarFilled = /*#__PURE__*/ wrapIcon(StarFilledBase, 'StarFilled');
export const HeartRegular = /*#__PURE__*/ wrapIcon(HeartRegularBase, 'HeartRegular');
export const HeartFilled = /*#__PURE__*/ wrapIcon(HeartFilledBase, 'HeartFilled');
export const LockClosedRegular = /*#__PURE__*/ wrapIcon(LockClosedRegularBase, 'LockClosedRegular');
export const LockClosedFilled = /*#__PURE__*/ wrapIcon(LockClosedFilledBase, 'LockClosedFilled');
export const ColorRegular = /*#__PURE__*/ wrapIcon(ColorRegularBase, 'ColorRegular');
export const ColorFilled = /*#__PURE__*/ wrapIcon(ColorFilledBase, 'ColorFilled');
export const PaintBrushRegular = /*#__PURE__*/ wrapIcon(PaintBrushRegularBase, 'PaintBrushRegular');
export const PaintBrushFilled = /*#__PURE__*/ wrapIcon(PaintBrushFilledBase, 'PaintBrushFilled');
export const TextFontRegular = /*#__PURE__*/ wrapIcon(TextFontRegularBase, 'TextFontRegular');
export const TextFontFilled = /*#__PURE__*/ wrapIcon(TextFontFilledBase, 'TextFontFilled');
export const KeyboardRegular = /*#__PURE__*/ wrapIcon(KeyboardRegularBase, 'KeyboardRegular');
export const KeyboardFilled = /*#__PURE__*/ wrapIcon(KeyboardFilledBase, 'KeyboardFilled');
export const CodeRegular = /*#__PURE__*/ wrapIcon(CodeRegularBase, 'CodeRegular');
export const CodeFilled = /*#__PURE__*/ wrapIcon(CodeFilledBase, 'CodeFilled');
export const StackRegular = /*#__PURE__*/ wrapIcon(StackRegularBase, 'StackRegular');
export const StackFilled = /*#__PURE__*/ wrapIcon(StackFilledBase, 'StackFilled');
export const CompassNorthwestRegular = /*#__PURE__*/ wrapIcon(CompassNorthwestRegularBase, 'CompassNorthwestRegular');
export const CompassNorthwestFilled = /*#__PURE__*/ wrapIcon(CompassNorthwestFilledBase, 'CompassNorthwestFilled');
export const MaximizeRegular = /*#__PURE__*/ wrapIcon(MaximizeRegularBase, 'MaximizeRegular');
export const MaximizeFilled = /*#__PURE__*/ wrapIcon(MaximizeFilledBase, 'MaximizeFilled');
export const SquareMultipleRegular = /*#__PURE__*/ wrapIcon(SquareMultipleRegularBase, 'SquareMultipleRegular');
export const SquareMultipleFilled = /*#__PURE__*/ wrapIcon(SquareMultipleFilledBase, 'SquareMultipleFilled');
export const ClockRegular = /*#__PURE__*/ wrapIcon(ClockRegularBase, 'ClockRegular');
export const ClockFilled = /*#__PURE__*/ wrapIcon(ClockFilledBase, 'ClockFilled');
export const HistoryRegular = /*#__PURE__*/ wrapIcon(HistoryRegularBase, 'HistoryRegular');
export const HistoryFilled = /*#__PURE__*/ wrapIcon(HistoryFilledBase, 'HistoryFilled');
export const GlobeRegular = /*#__PURE__*/ wrapIcon(GlobeRegularBase, 'GlobeRegular');
export const GlobeFilled = /*#__PURE__*/ wrapIcon(GlobeFilledBase, 'GlobeFilled');
export const CloudRegular = /*#__PURE__*/ wrapIcon(CloudRegularBase, 'CloudRegular');
export const CloudFilled = /*#__PURE__*/ wrapIcon(CloudFilledBase, 'CloudFilled');
export const PhoneRegular = /*#__PURE__*/ wrapIcon(PhoneRegularBase, 'PhoneRegular');
export const PhoneFilled = /*#__PURE__*/ wrapIcon(PhoneFilledBase, 'PhoneFilled');
export const DesktopRegular = /*#__PURE__*/ wrapIcon(DesktopRegularBase, 'DesktopRegular');
export const DesktopFilled = /*#__PURE__*/ wrapIcon(DesktopFilledBase, 'DesktopFilled');
export const WeatherMoonRegular = /*#__PURE__*/ wrapIcon(WeatherMoonRegularBase, 'WeatherMoonRegular');
export const WeatherMoonFilled = /*#__PURE__*/ wrapIcon(WeatherMoonFilledBase, 'WeatherMoonFilled');
export const WeatherSunnyRegular = /*#__PURE__*/ wrapIcon(WeatherSunnyRegularBase, 'WeatherSunnyRegular');
export const WeatherSunnyFilled = /*#__PURE__*/ wrapIcon(WeatherSunnyFilledBase, 'WeatherSunnyFilled');
